### ISSUE TITLE
Could not find com.github.kittinunf.result:result:3.0.0.

### ISSUE THREAD

**Issue by jisungbin** [arunkumar9t2/scabbard#100]
I am using the latest version 0.5.0, and when I build it, the below error occurs:
```
Could not determine the dependencies of task ':presentation:kaptDebugKotlin'.
> Could not resolve all task dependencies for configuration ':presentation:kaptClasspath_kaptDebugKotlin'.
   > Could not find com.github.kittinunf.result:result:3.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/kittinunf/result/result/3.0.0/result-3.0.0.pom
       - https://repo.maven.apache.org/maven2/com/github/kittinunf/result/result/3.0.0/result-3.0.0.pom
     Required by:
         project :presentation > dev.arunkumar:scabbard-processor:0.5.0
```

I think `com.github.kittinunf.result:result:3.0.0` was removed from Maven. Can you replace this dependency with the latest version?

![image](https://user-images.githubusercontent.com/40740128/151852997-b1b17d40-c051-4854-9620-aa9e9961642f.png)

Here is Maven link: [search.maven.org/search?q=g:com.github.kittinunf.result](https://search.maven.org/search?q=g:com.github.kittinunf.result)

**Comment by arunkumar9t2** [comment]
Hi thanks for reporting, it is fixed in `main` but I have not published a new version. I will try to do asap. Meanwhile please follow the changes in this PR. 

https://github.com/arunkumar9t2/scabbard-sample/pull/1/files

**Comment by jisungbin** [comment]
Thanks for the quick reply! I think I solved it!!
Should I close the issue?

**Comment by overheadhunter** [comment]
Sadly the workaround doesn't work for Maven projects, as Maven's dependency management doesn't work for annotation processors. So could you please release a new version with the `3.0.1` dependency?

**Comment by arunkumar9t2** [comment]
Hi thanks for raising this up, I will try to release hot fix asap.
