### ISSUE TITLE
ScabbardPluginExtension is not configurable from Kotlin

### ISSUE THREAD

**Issue by ZacSweers** [arunkumar9t2/scabbard#13]
We have a Gradle plugin that manages setup of our standard project configurations and is written in Kotlin. Most Gradle plugins use a simple interface or abstract class for their plugin extension, but scabbard appears to use an undocumented `Configurable` Gradle API that accepts an untyped `Closure`. The result is we can't configure this extension from Kotlin as the underlying `ScabbardSpec` is not accessible outside of groovy's magic duck typing.

I'd recommend using a standard plugin API, unless `Configurable` offers some specific functionality that scabbard needs.

**Comment by arunkumar9t2** [comment]
Thanks, I understand this is a problem. I gave some background for this in #15. I am still looking for best way to fix this.

As an workaround, please let me know if the below works?

```kotlin
val scabbard = extensions.getByName("scabbard") as dev.arunkumar.scabbard.gradle.ScabbardPluginExtension

scabbard.configure(closureOf<ScabbardSpec> {
    // Configure here
    enabled(true)
})
```

Not the best syntax I know, will continue investigation this. Please let me know if this works, I can update FAQ.

**Comment by ZacSweers** [comment]
Where is the `closureOf()` function defined? We're not using Gradle's kotlin-dsl, it's just a gradle plugin written in kotlin.

**Comment by ZacSweers** [comment]
To be clear - I don't see this function in kotlin-dsl either, but mentioning just in case

**Comment by ZacSweers** [comment]
Well actually, I see it here now https://gradle.github.io/kotlin-dsl-docs/api/org.gradle.kotlin.dsl/kotlin.-any/closure-of.html. Didn't realize it's an extension function on `Any` rather than a free type like the sample snippet seemed to suggest (maybe it's implicitly relying on `project`?)`. Will try out your workaround, though not enthused about it potentially requiring kotlin-dsl :/. Hopefully I can copy their implementation out

**Comment by ZacSweers** [comment]
That appears to work, so I'll close this out. Wish Gradle would properly document that `Configurable` class

**Comment by arunkumar9t2** [comment]
I think it is added to `Any` just to prevent it being accessed statically and only as an instance method.

Here is the [source ](https://github.com/gradle/gradle/blob/master/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/GroovyInteroperability.kt#L38)for `closureOf`.
