### ISSUE TITLE
Refactor Scabbard Gradle Plugin extension

### ISSUE THREAD

**Issue by arunkumar9t2** [arunkumar9t2/scabbard#15]
### Summary
Scabbard's Gradle plugin currently relies on Groovy meta-programming to configure the extension, which makes it hard/confusing for Kotlin users as the syntax can be weird due to typing issues. 

### Background
Early development versions did use standard plugin configuration design like
```
scabbard { //this : ScabbardPluginExtension
}
```
However this caused issues when reading user configured values from extension and configuring the project. Scabbard mainly does two things:
1. Add scabbard's processor dependency to project
2. Delegate user configured values as compiler options to annotation processors (scabbard's and dagger's)

[This](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:getting_input_from_the_build) example from Gradle does not apply here because `extension.message` is only used on `doLast {}` which is well into execution phase and by then Gradle would have configured the extension and user defined values would have been read.

In Scabbard's case, we need to execute 1 and 2 above in configuration phase but after gradle configures `ScabbardPluginExtension`. Current problems:

* If 1 and 2 are executed immediately when plugin is applied i.e in `Plugin.apply(project`), user defined properties are not read since `scabbard { }` block is not available yet.
* If 1 and 2 are executed in `afterEvaluate {}` then user defined properties are read which is good but can't apply annotation processor options anymore ([details](https://github.com/arunkumar9t2/scabbard/issues/15#issuecomment-570910086)).

## Workaround

We need to execute 1 and 2 above as and when Gradle configures the extension, one way to do that is to use `Configurable` interface and do 1 and 2 in `configure(closure: Closure<*>)` block. While this works, the syntax is unpleasant since type information is lost.

## What other are doing

- [Realm plugin](https://github.com/realm/realm-java/tree/master/gradle-plugin) also adds project dependencies and to solve the user defined values reading problem, they [register a listener](https://github.com/realm/realm-java/blob/5a1a25c764bdb4eef71d04103b0b3c75006fa9d7/gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy#L56) and execute dependencies logic everytime it changes.
- Intellij plugin seems to [track execution state](https://github.com/JetBrains/gradle-intellij-plugin/blob/c2b1b42b642c7e898c84fa7f631d35624adeb09b/src/main/groovy/org/jetbrains/intellij/IntelliJPlugin.groovy#L216) with `project.state.executed` and then determine if dependencies can be applied.

## Current solution.

1. Groovy
    ```groovy
     scabbard {
         enabled true
     }
    ```
2. Kotlin
    ```kotlin
    scabbard.configure(closureOf<ScabbardSpec> {
      enabled(true)
    })
    ```

## Nice to have

```
scabbard { // this : ScabbardPluginExtension
   // properties from extension
}
```

**Comment by autonomousapps** [comment]
I'm confused by this statement:
> If 1 and 2 are executed in `afterEvaluate {}` then user defined properties are read which is good but we can't modify the project dependencies or apply annotation processor options anymore since config phase is over.

It was not my understanding that the "config phase is over" in an `afterEvaluate` block. Did you test that and it failed?

**Comment by arunkumar9t2** [comment]
Yeah you are correct, I need to fix the wording. If I move the logic to `afterEvaluate {}` these are my findings:

- Able to add scabbard dependencies correctly, the extension has user configured values
- Passing compiler options to `javac` and `kapt` does not work. The [code ](https://github.com/arunkumar9t2/scabbard/blob/004116cf6a548022982c7869d7758725c18991f8/scabbard-gradle-plugin/src/main/kotlin/dev/arunkumar/scabbard/gradle/propertiesdelegate/ScabbardPropertiesDelegate.kt#L24)is getting executed, but options that are passed are not actually read by the compiler. Not sure why.

Did some reading and it seems like [Provider](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/Provider.html) can help in solving the problem by receiving callbacks when the properties change as described in [Lazy Configuration.](https://docs.gradle.org/current/userguide/lazy_configuration.html)

**Comment by autonomousapps** [comment]
I use providers and properties exclusively now in my Gradle plugins. They
solve a lot of problems.
