### ISSUE TITLE
guru.nidi.graphviz.engine.GraphvizException: Initializing graphviz engine took too long.

### ISSUE THREAD

**Issue by Saba-21** [arunkumar9t2/scabbard#30]
hi, i set `failOnError true` and got following error

**Comment by arunkumar9t2** [comment]
Hello, may I know if you have installed `dot` command and it is available to be invoked from command line?

**Comment by sabafromwandio** [comment]
@arunkumar9t2 Hello, yes, dot -V returns - 

> dot - graphviz version 2.38.0 (20140413.2041)

**Comment by arunkumar9t2** [comment]
Quick search points to this https://github.com/nidi3/graphviz-java/issues/41. Let me investigate if anything can be done from Scabbard. May I know your OS version?

**Comment by sabafromwandio** [comment]
windows 10 pro v1903 64-bit

**Comment by arunkumar9t2** [comment]
Thanks, I will investigate.

**Comment by Saba-21** [comment]
@arunkumar9t2 fixed in 0.2.0, you can close this issue, great job, keep developing
