### ISSUE TITLE
scabbard icon doesn't show after Studio plugin installation

### ISSUE THREAD

**Issue by adroitandroid** [arunkumar9t2/scabbard#43]
hi, thanks for coming up with this!

I have installed the plugin in Android Studio 3.5.3 and also done graphViz installation such that dot -V is returning the version.

I've restarted the Android Studio since doing all the above. Yet I'm unable to get the dagger icon against my dagger subcomponents, components, modules...

What am I missing? Is there any build/run/tools/analyze menu item that will also show up, which I could use instead?

**Comment by arunkumar9t2** [comment]
Hello could you confirm if you have applied the gradle plugin as well and have issued a build? The files are generated during build and icons would be only added after that.

**Comment by adroitandroid** [comment]
added the gradle plugin and it's working all right now, thanks
