### ISSUE TITLE
I don't see gutter icon on my intellj idea after installing plugin

### ISSUE THREAD

**Issue by speedysingh786** [arunkumar9t2/scabbard#50]
Dagger 2 version 2.24
Scabbard version 0.3.0
intellj version 2020.1.1
I'm using Maven 3.3 to build my project

**Comment by NaturallyAsh** [comment]
This happened to me.  File -> Invalidate Caches/Restart.  When it starts up again, if you still do not see the gutter icon, try Build -> Rebuild project.

**Comment by arunkumar9t2** [comment]
@speedysingh786 Scabbard generates images during build and IDE plugin simply links the generated images to respective components. It was built for Gradle but it is possible to make it work with Maven as well.

I have just updated the docs here explaining how to configure for maven projects: https://arunkumar9t2.github.io/scabbard/configuration/#maven

Please try this and let me know should you run into any issues. Closing for now, thanks.
