### ISSUE TITLE
Bump to Kotlin 1.4.20

### ISSUE THREAD

**Issue by AlexShafir** [arunkumar9t2/scabbard#67]
My project uses Kotlin 1.4.20 (latest release).
After I installed Scabbard, project was built successfully.
However, IDE started to show error "Kotlin plugin version is not the same as library version”.

It seems that Scabbard indeed uses Kotlin 1.3.72: https://github.com/arunkumar9t2/scabbard/blob/0.4.0/constants.gradle

**Comment by arunkumar9t2** [comment]
Thanks for reporting, I will work on updating to 1.4.+ for next release.
